[package]
name = "tetris"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
# bevy
bevy = { version = "0.16.1", features = ["dynamic_linking"] }

# other
rand = "0.9.2"
rand_chacha = "0.9.0"
tracing = "0.1.41"

